[[redirects]]
  from = "http://odyexc.com/*"
  to = "https://www.odyexc.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.odyexc.com/*"
  to = "https://www.odyexc.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://odyexc.com/*"
  to = "https://www.odyexc.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"  # This is the correct output directory for Vite

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-Robots-Tag = "index, follow"
